---
# roles/prepare_folders/tasks/main.yml

- name: Ensure E:\AdminAppFiles exists
  win_file:
    path: "E:\\AdminAppFiles"
    state: directory
  tags:
    - prepare_folders
    - folders

- name: Ensure E:\AppBackups exists
  win_file:
    path: "E:\\AppBackups"
    state: directory
  tags:
    - prepare_folders
    - folders

- name: Ensure E:\InstallFiles exists
  win_file:
    path: "{{ remote_dir }}"
    state: directory
  tags:
    - prepare_folders
    - folders

- name: Ensure E:\AdminAppFiles\ScheduledTaskScripts exists
  win_file:
    path: "E:\\AdminAppFiles\\ScheduledTaskScripts"
    state: directory
  tags:
    - prepare_folders
    - folders

- name: Transfer & extract install files if needed
  block:
    - name: Check for unpack marker
      win_stat:
        path: "{{ marker_file }}"
      register: marker_stat
      tags:
        - prepare_folders
        - transfer

    - name: Copy install_files.zip to remote
      win_copy:
        src: "{{ local_zip }}"
        dest: "{{ remote_zip }}"
        checksum: yes
      when: not marker_stat.stat.exists
      tags:
        - prepare_folders
        - transfer

    - name: Unzip install_files.zip
      win_unzip:
        src: "{{ remote_zip }}"
        dest: "{{ remote_dir }}"
      register: unzip_result
      when: not marker_stat.stat.exists
      tags:
        - prepare_folders
        - transfer

    - name: Create unpack marker file
      win_file:
        path: "{{ marker_file }}"
        state: touch
      when: unzip_result.changed
      tags:
        - prepare_folders
        - transfer

  rescue:
    - name: Report transfer/unzip failure
      win_shell: |
        Write-Error "❌ Failed to transfer or unzip install files on {{ inventory_hostname }}"
      tags:
        - prepare_folders
        - transfer

- name: Clean up remote ZIP file
  win_file:
    path: "{{ remote_zip }}"
    state: absent
  tags:
    - prepare_folders
    - cleanup
