#
# Module manifest for module 'ThemeForge'
#
# Generated by: Jeremiah Williams
#
# Generated on: 1/13/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ThemeForge.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Core', 'Desktop')

# ID used to uniquely identify this module
GUID = 'fd4bfcec-68c7-4898-8242-7127f855608f'

# Author of this module
Author = 'Jeremiah Williams'

# Copyright statement for this module
Copyright = '(c) Jeremiah Williams. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This module helps manage themes for Windows Terminal.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '3.0'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('New-ThemeForge', 'Get-ThemeForge', 'Change-ThemeForge', 'Update-ThemeForge', 'Export-ThemeForge', 'Remove-ThemeForge', 'Show-ThemeForge')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @('stf', 'ntf', 'gtf', 'utf', 'rtf', 'ctf', 'etf')

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Windows Terminal', 'Themes', 'PowerShell', 'Automation')

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/jthamind/ThemeForge'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Initial release with core functionality for managing Windows Terminal themes.'

    }
}
}

