---
- name: Configure CP Servers (all steps)
  hosts: all
  gather_facts: no

  roles:
    - role: prepare_folders
      tags: [prepare_folders]

    - role: install_iis
      tags: [install_iis]

    - role: install_dotnet
      tags: [install_dotnet]

    - role: install_utilities
      tags: [install_utilities]

    - role: schedule_tasks
      tags: [schedule_tasks]

    - role: install_tentacle
      tags: [install_tentacle]

    - role: install_software
      tags: [install_software]

    - role: post_reboot_validation
      tags: [post_reboot_validation]
