---
- name: Install Notepad++ and Neovim on Windows Server
  hosts: all
  gather_facts: no

  tasks:
    - name: Check if Notepad++ is already installed
      win_stat:
        path: "C:\\Program Files\\Notepad++\\notepad++.exe"
      register: notepadpp_check

    - name: Check if Notepad++ installer exists
      win_stat:
        path: "E:\\InstallFiles\\npp.8.5.8.Installer.x64.exe"
      register: notepadpp_installer

    - name: Install Notepad++ silently
      win_package:
        path: "E:\\InstallFiles\\npp.8.5.8.Installer.x64.exe"
        arguments: /S
        state: present
      when:
        - not notepadpp_check.stat.exists
        - notepadpp_installer.stat.exists

    - name: Warn if Notepad++ installer is missing
      debug:
        msg: "⚠️ Notepad++ installer not found at \"E:\\InstallFiles\\npp.8.5.8.Installer.x64.exe\". Skipping install."
      when:
        - not notepadpp_check.stat.exists
        - not notepadpp_installer.stat.exists

    - name: Check if Neovim directory already exists
      win_stat:
        path: "E:\\AdminAppFiles\\nvim-win64\\bin\\nvim.exe"
      register: nvim_dir_status

    - name: Check if Neovim folder is available on install files
      win_stat:
        path: "E:\\InstallFiles\\nvim-win64"
      register: nvim_src_check

    - name: Copy nvim-win64 folder to E:\\AdminAppFiles
      win_copy:
        src: "E:\\InstallFiles\\nvim-win64"
        dest: "E:\\AdminAppFiles"
        remote_src: yes
      when:
        - not nvim_dir_status.stat.exists
        - nvim_src_check.stat.exists

    - name: Warn if Neovim folder not found at E:\\InstallFiles
      debug:
        msg: "⚠️ Neovim folder not found at \"E:\\InstallFiles\\nvim-win64\". Skipping copy."
      when:
        - not nvim_dir_status.stat.exists
        - not nvim_src_check.stat.exists

    - name: Add Neovim and Notepad++ to the machine-level PATH
      ansible.windows.win_path:
        scope: machine
        state: present
        elements:
          - 'E:\AdminAppFiles\nvim-win64\bin'
          - 'C:\Program Files\Notepad++'
      register: path_env_update

    - name: Reboot after software install (to refresh WinRM env + PATH)
      win_reboot:
        reboot_timeout: 600
        msg: "Rebooting after software installation to apply system PATH changes."
      when: path_env_update.changed

